spring:
  application:
    name: manajemenrisiko
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/manajemen_risiko}
    username: ${DB_USERNAME:majapahit}
    password: ${DB_PASSWORD:Madiun@123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  validation:
    enabled: true
  main:
    banner-mode: off

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true

logging:
  level:
    root: warn
    org:
      hibernate:
        SQL: trace
        orm:
          jdbc:
            bind: trace
      springdoc: DEBUG
      springframework:
        web: DEBUG
    io:
      swagger: DEBUG
    com:
      luv2code:
        springboot:
          aopdemo: INFO

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    disable-swagger-default-url: true
  override-with-generic-response: false
  show-actuator: false