apiVersion: apps/v1
kind: Deployment
metadata:
  name: manrisk-opd-service
  labels:
    app: manrisk-opd-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manrisk-opd-service
  template:
    metadata:
      labels:
        app: manrisk-opd-service
    spec:
      containers:
        - name: manrisk-opd-service
          image: manrisk-opd-service
          imagePullPolicy: Never
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 8080
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://kertaskerja-postgres:5432/manajemen_risiko

