apiVersion: v1
kind: Service
metadata:
  name: manrisk-opd-service
  labels:
    app: manrisk-opd-service
spec:
  type: ClusterIP
  selector:
    app: manrisk-opd-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080